name: Continuous Deployment (CD) ðŸš€

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Selecciones el/los entornos a desplegar"
        required: true
        default: "qa"
        type: choice
        options:
          - qa
          - prod
      artifact:
        description: "Selecciona el artefacto"
        required: true
        type: string

run-name: ${{ 'Deploy in EKS - ${{ inputs.environment }} - ${{ inputs.tag }}' }}

jobs:
  CD:
    name: ${{ 'CD - ${{ inputs.environment }}' }}
    uses: the-palace-company/github-actions/.github/workflows/cd-be-main.yml@main
    with:
      ENVIRONMENT: ${{ '${{ inputs.environment }}' }}
      ARTIFACT: ${{ '${{ inputs.artifact }}' }}
      department: operaciones
    secrets: inherit
